version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kptriescoding/dpms-backend
    container_name: dpms-backend
    volumes:
      - ./backend/:/usr/src/backend
      - /usr/src/backend/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - mysql
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/mongodb
    ports:
      - "27017:27017"

    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kptriescoding/dpms-client
    container_name: dpms-client
    volumes:
      - ./client/:/usr/src/client
      - /usr/src/client/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
  mysql:
    image: mysql
    volumes:
      - data-volume:/data/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dpms-mysql123
    networks:
      - app-network
networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local